data:
  train:
    datasets:
      - name: COCOInstance
        json_file: ./data/MSCOCO/annotations/instances_train2017.json
        image_root: ./data/MSCOCO/train2017/
        metadata:
          name: COCOInstanceMetadata
#      - name: COCOInstance
#        json_file: ./data/MSCOCO/annotations/instances_train2017.json
#        image_root: ./data/MSCOCO/train2017/
#        metadata:
#          name: COCOInstanceMetadata
    pipelines:
      - name: CrowdFilter
      - name: FewKeypointsFilter
        min_keypoints_per_image: 0
    transform_gens:
      - name: RandomApply
        transform:
          name: RandomHFlip
      - name: RandomHFlip
      - name: RandomVFlip
      - name: Resize
        shape: 100
      - name: ResizeShortestEdge
        short: 600
        max_size: 1000
        sample_style: range
      - name: RandomCrop
        crop_type: absolute
        crop_size: [600, 600]
      - name: RandomContrast
        intensity_min: 0.5
        intensity_max: 1.2
      - name: RandomBrightness
        intensity_min: 0.5
        intensity_max: 1.2
      - name: RandomSaturation
        intensity_min: 0.5
        intensity_max: 1.2
      - name: RandomLighting
        scale: 0.5
      - name: RandomRotation
        angle: 200
      - name: RandomExtent
        scale_range: [0.5, 1.2]
        shift_range: [0.1, 0.2]

dataloader:
  images_per_gpu: 2
  num_workers: 4

model:
  name: FasterRCNN
  backbone:
    name: ResNet
    depth: 50
  neck:
    name: FPN
  proposal_head:
    name: RPN
    anchor_generator:
      name: StandardAnchorGenerator
  roi_head:
    name: ROIHead
  device: cuda

cudnn_benchmark: False
output_dir: ./experiments/demo
seed: 1234
