data:
  train:
    datasets:
      - name: COCOInstance
        json_file: ./data/MSCOCO/annotations/instances_train2017.json
        image_root: ./data/MSCOCO/train2017/
        metadata:
          name: COCOInstanceMetadata
#      - name: COCOInstance
#        json_file: ./data/MSCOCO/annotations/instances_train2017.json
#        image_root: ./data/MSCOCO/train2017/
#        metadata:
#          name: COCOInstanceMetadata
    pipeline:
      - name: CrowdFilter
      - name: FewKeypointsFilter
        min_keypoints_per_image: 0
    transforms:
      - name:

dataloader:
  images_per_gpu: 2
  num_workers: 4

model:
  name: FasterRCNN
  backbone:
    name: ResNet
    depth: 50
  neck:
    name: FPN
  proposal_head:
    name: RPN
    anchor_generator:
      name: StandardAnchorGenerator
  roi_head:
    name: ROIHead
  device: cuda

cudnn_benchmark: False
output_dir: ./experiments/demo
seed: 1234
