data:
  train:
    datasets:
#      - name: COCOInstance
#        json_file: ./data/MSCOCO/annotations/instances_train2017.json
#        image_root: ./data/MSCOCO/train2017/
#        metadata:
#          name: COCOInstanceMetadata
      - name: COCOInstance
        json_file: ./data/MSCOCO/annotations/person_keypoints_train2017.json
        image_root: ./data/MSCOCO/train2017/
        metadata:
          name: COCOPersonMetadata
    pipelines:
      - name: CrowdFilter
      - name: FewKeypointsFilter
        min_keypoints_per_image: 0
      - name: AnnotationPopup
        mask_on: True
        keypoint_on: True
    dataset_mapper:
      name: DictMapper
      transforms:
        - name: RandomCrop
          crop_type: absolute
          crop_size: [600, 600]
        - name: RandomHFlip
        - name: ResizeShortestEdge
          short: 600
          max_size: 1000
          sample_style: range

dataloader:
  train:
    sampler:
      name: TrainingSampler
    aspect_ratio_grouping: True
    images_per_batch: 2
    num_workers: 0
  test:
    num_workers: 0


model:
  name: FasterRCNN
  backbone:
    name: ResNet
    depth: 50
  neck:
    name: FPN
  proposal_head:
    name: RPN
    anchor_generator:
      name: StandardAnchorGenerator
  roi_head:
    name: ROIHead
  device: cuda

cudnn_benchmark: False
output_dir: ./experiments/demo
seed: 1234
