data:
  train:
    datasets:
#      - name: COCOInstance
#        json_file: ./data/MSCOCO/annotations/instances_train2017.json
#        image_root: ./data/MSCOCO/train2017/
      - name: COCOPerson
        json_file: ./data/MSCOCO/annotations/person_keypoints_train2017.json
        image_root: ./data/MSCOCO/train2017/
    pipelines:
      - name: CrowdFilter
      - name: FewKeypointsFilter
        min_keypoints_per_image: 0
      - name: AnnotationPopup
        mask_on: True
        keypoint_on: True
    mappers:
      - name: ImageLoader
      - name: ResizeShortestEdge
        short: 800
        max_size: 1333
        sample_style: choice
      - name: RandomHFlip
        prob: 0.5
      - name: ToInstances
  test:
    datasets:
      - name: COCOInstance
        json_file: ./data/MSCOCO/annotations/person_keypoints_val2017.json
        image_root: ./data/MSCOCO/val2017/
        metadata:
          name: COCOPersonMetadata
    mappers:
      - name: ImageLoader
      - name: ResizeShortestEdge
        short: 800
        max_size: 1333
        sample_style: choice
      - name: ToInstances

dataloader:
  train:
    sampler:
      name: TrainingSampler
    aspect_ratio_grouping: True
    images_per_batch: 2
    num_workers: 0
  test:
    num_workers: 0


model:
  name: FasterRCNN
  backbone:
    name: ResNet
    depth: 50
  neck:
    name: FPN
  proposal_head:
    name: RPN
    anchor_generator:
      name: StandardAnchorGenerator
  roi_head:
    name: ROIHead
  device: cuda

cudnn_benchmark: False
output_dir: ./experiments/demo
seed: 1234
