data:
  train:
    datasets:
#      - name: COCOInstance
#        json_file: ./data/MSCOCO/annotations/instances_train2017.json
#        image_root: ./data/MSCOCO/train2017/
#        metadata:
#          name: COCOInstanceMetadata
      - name: COCOInstance
        json_file: ./data/MSCOCO/annotations/person_keypoints_train2017.json
        image_root: ./data/MSCOCO/train2017/
        metadata:
          name: COCOPersonMetadata
    pipelines:
      - name: CrowdFilter
      - name: FewKeypointsFilter
        min_keypoints_per_image: 0
      - name: FormatConverter
      - name: AnnotationPopup
        mask_on: True
        keypoint_on: True
    dataset_mapper:
      name: DictMapper
      transforms:
        - name: RandomApply
          transform:
            name: RandomHFlip
        - name: ExtentTransform
          src_rect: [0, 0, 0, 0]
          output_size: [100, 100]
        - name: RandomHFlip
        - name: RandomVFlip
        - name: Resize
          shape: 100
        - name: ResizeShortestEdge
          short: 600
          max_size: 1000
          sample_style: range
        - name: RandomCrop
          crop_type: absolute
          crop_size: [600, 600]

dataloader:
  images_per_gpu: 2
  num_workers: 4

model:
  name: FasterRCNN
  backbone:
    name: ResNet
    depth: 50
  neck:
    name: FPN
  proposal_head:
    name: RPN
    anchor_generator:
      name: StandardAnchorGenerator
  roi_head:
    name: ROIHead
  device: cuda

cudnn_benchmark: False
output_dir: ./experiments/demo
seed: 1234
